default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: camronkhan_development
  username: postgres
  password: <%= ENV['DEV_PASSWORD'] %>

test:
  <<: *default
  database: camronkhan_test
  username: postgres
  password: <%= ENV['DEV_PASSWORD'] %>

production:
  <<: *default
  database: camronkhan_production
  username: camronkhan
  password: <%= ENV['DEV_PASSWORD'] %>